<?php
/**
* Implements hook_menu().
*/
function dss_readspeakerblock_menu() {
	$items = array();
	$items['admin/config/user-interface/dss_readspeakerblock'] = array(
		'title' => 'DSS ReadSpeaker Block',
		'description' => 'Configuration for the DSS ReadSpeaker Block module.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('dss_readspeakerblock_form'),
		'access arguments' => array('administer blocks'),
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

/**
* Form builder
*/
function dss_readspeakerblock_form($form, &$form_state) {
	$dss_readspeakerblock_settings = variable_get('dss_readspeakerblock_settings');
	$form['general'] = array(
		'#type' => 'fieldset',
		'#title' => t('General Options'),
		'#tree' => TRUE,
	);
	$form['general']['customerid'] = array(
		'#type' => 'textfield',
		'#title' => t('Customer ID'),
		'#default_value' => t($dss_readspeakerblock_settings['customerid']),
		'#description' => t("Your ReadSpeaker Cutomer ID"),
		'#size' => 4,
		'#maxlength' => 4,
	);
	$form['general']['readid'] = array(
		'#type' => 'textfield',
		'#title' => t('Read ID'),
		'#default_value' => t($dss_readspeakerblock_settings['readid']),
		'#description' => t("The ID of the page element to be read"),
		'#size' => 32,
		'#maxlength' => 32,
	);
	// Submit button
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save settings')
		);
	return $form;
}

/**
* Save configuration settings
*/
function dss_readspeakerblock_form_submit($form, &$form_state) {
	// Check and Set Variables
	$dss_readspeakerblock_settings = array(
		'customerid' => $form_state['values']['general']['customerid'],
		'readid' => $form_state['values']['general']['readid'],
	);
	variable_set('dss_readspeakerblock_settings',$dss_readspeakerblock_settings);
	//Settings saved
	drupal_set_message(t('The settings have been saved'));
}

/**
 * Implements hook_block_info().
 */
function dss_readspeakerblock_block_info() {
	$blocks['dss_readspeakerblock'] = array(
		'info' => t('DSS ReadSpeaker Block (Module)'),
		'cache' => DRUPAL_NO_CACHE,
	);
	return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function dss_readspeakerblock_block_configure($delta) {
	$form = array();
	$form['textfield'] = array(
		'#type' => 'markup',
		'#markup' => '<p><a href="/admin/config/user-interface/dss_readspeakerblock">Configuration</a></p><br />',
	);
	return $form;
}

/**
 * Implements hook_block_view().
 */
function dss_readspeakerblock_block_view() {
	$dss_readspeakerblock_settings = variable_get('dss_readspeakerblock_settings');
	$customerid = $dss_readspeakerblock_settings['customerid'];
	$readid = $dss_readspeakerblock_settings['readid'];
	$proto = 'http';
	if (isset($_SERVER['HTTPS'])) {
		if ($_SERVER['HTTPS'] != '') $proto = 'https';
	}
	// Attach ReadSpeaker's script from CDN
	drupal_add_js($proto.'://cdn1.readspeaker.com/script/'.$customerid.'/webReader/webReader.js?pids=wr&notools=1',array('group' => JS_DEFAULT, 'type' => 'file', 'scope'=>'footer', 'preprocess' => FALSE));
	// Set rsConf Options
	drupal_add_js('window.rsConf = { ui: { disableDetachment: true, displayDownload: false }};', array('type' => 'inline','scope' => 'header'));
	// Prepare the code
	$formatted = '<div id="readspeaker_button" class="rs_skip rsbtn rs_preserve">';
	$formatted .= '<a rel="nofollow" class="rsbtn_play" href="//app-oc.readspeaker.com/cgi-bin/rsent?customerid='.$customerid.'&amp;lang=en_au&amp;readid='.$readid.'&amp;url='.$proto.'://'.$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"].'">';
	$formatted .= '<span class="rsbtn_left rspart rsimg"><span class="rsbtn_text"><span>Listen</span></span></span><span class="rsbtn_right rsimg rsplay rspart"></span></a></div>';
 	$block['subject'] = '';
	$block['content'] = $formatted;
	return $block;
}
