<?php
// Install module
function dss_readspeakerblock_install() {
	// Plugin defaults
	$dss_readspeakerblock_settings = array(
		'customerid' => '5931',
		'readid' => 'content',
		'popupplayer' => true,
	);
	variable_set('dss_readspeakerblock_settings', $dss_readspeakerblock_settings);
}
// Uninstall module
function dss_readspeakerblock_uninstall() {
	variable_del('dss_readspeakerblock_settings');
}
